### ISSUE TITLE
1. katselmus

### ISSUE THREAD

**Issue by pparm** [Sihuvi84/Tsoha-Bootstrap#1]
Projekti ladattu su, maalis 22 2015 23:42:20

Hienoa ja selkeätä työtä. Dokumentaatio on selkeä, havainnollinen ja helposti luettava. Koska käyttöliittymän ja järjestelmäkomponenttien dokumentaatiota ei vaadita toisessa palautuksessa, on graafiseen käyttöliittymään vaikeampi tutustua. Graafisen käyttöliittymän näkymät ovat selkeitä ja intuitiivisia.

HUOMIOITA:

Dokumentointi:

Jos johdantoa haluaa hieman viilata voisi lyhennelmää MVC-mallia vähän avata Suomeksi. Käsite on varmaankin yleisesti tunne, mutta voisii olla hyvä kerran mainita tarkemmmin mikä se on.

Käyttötapauskaaviossa on Kirjautunut käyttäjä ja Ylläpitäjä. Kaipasin uutta käyttäjää. Nyt tulee mielikuva, että käyttäjäksi pääsee ainoastaan ottamalla yhteyttä Ylläpitäjään. Tämä voi toki olla ainoa mahdollinen työnkulku. Käytännön elämässä asiakkaan omatoiminen rekisteröityminen helpottaa merkittävästi ylläpitoa.

Luokkakaavio noudatti hyvin käsitekaaviota.
GUI:

Linkki README.md Linkki sovellukseen vie sivulle, jossa lukee "Tämä on etusivu". Jonkilainen sivu lienee täytynee olla ja lienee jo työn alla.

Askareiden listauksessa voisi olla linkki, joka avaisi askareen pitemässä muodossa. Nämä leiskat ovat varmasti kehityksen alla.

Tietorakenne:

Tietokannan taulut noudattavat hyvin dokumentissa olevia. Rooli-luokan tarpeellisuus jäi hieman mietityttämään. Voisiko rooli olla Kayttaja-luokan attribuutti. Jos käyttäjällä voi olla monta roolia yhtä aikaa, lienee valittu ratkaisu paras.

En löytänyt ainoatakaan monesta moneen kytkentää, joka tarvittaneen hyvään arvosanaan.

Sovelluksen läpikäyminen oli helppoa ja antoisaa. Sain myös muutamia vinkkejä itselleni. Pikkasen on vielä tekemistä, mutta olet hyvin pysynyt pulkassa mukana.

**Comment by Sihuvi84** [comment]
Hei, kiitos erittäin hyödyllisestä palautteesta.

Dokumentointi: palautteesi johdosta aion avata johdantoon MVC-mallia. Lisäksi aion lisätä uuden käyttötapauksen: rekisteröityminen. Harkitsin aluksikin kyseisen käyttötapauksen lisäystä, mutta jostain syystä en päätynyt sitä heti mukaan ottamaan. Lisäksi aion hieman muokata kappaletta "Järjestelmän tietosisältö". Huomasin, että olin kirjannut käsitekaavioonkin relaatiokaavioon mukaani ottaman välitaulun "Askareluokka". Tämä välitaulu tarvitaan, jotta monen-suhde-moneen-kytkentä saadaan toteuttua tietokantaan käytännössä. Huomaamasi puuttuva monen-suhde-moneen-kytkentä siis on kyllä tietosisällöllisesti olemassa, mutta on tapana tietokantaa suunnitellessa purkaa monen-suhde-moneen, esimerkiksi tekemällä kahden taulun väliin välitaulu. Monen-suhde-moneen-kytkentä  siis on Askareen ja Luokan välillä. 

Hups, tosiaan - oli jäänyt yksi linkki README-md tiedostoon osoittamaan väärin - kiitos huomiosta.

Kiitos hyvistä huomioista, aion ottaa ne huomioon jatkaessani työtä. Palautteesi oli erittäin hyödyllistä.
