### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by emmakamarainen** [Sihuvi84/Tsoha-Bootstrap#2]
ladattu 13.4.2015 klo 20:13

Katselin ensin koodiasi, se näyttää hyvältä: kaikki on nimetty selkeästi ja kansiorakennekin on hyvä (modelit omissa kansioissaan). Toki tällä kurssilla kun repo forkattiin niin sitä ei saakkaan samalla lailla sekasin kun itse luodessa pystyisi :) 

Html-sivuja on luotu mukavasti, ulkoasukin poikkeaa viihdyttävästi materiaalissa olevasta ulkoasusta. Vaihda salasana- linkki ei toimi vielä, mutta oletkin siitä varmaan tietoinen. Hieman ihmettelin myös askareiden luokitusta, kun kaikki ovat lemmikit-luokassa. Kaipailin myös käyttäjätunnusta ja salasanaa, joilla testata mutta en nopeasti niitä löytänyt. Kaivoin Saunatontun salasanan esille ja kokeilin kirjautua: joko typosin itse tai sitten kirjautuminen ei toimi vielä. En myöskään osannut testata salasananvaihtoa. Poistaminen tosin toimii (sori, poistin osan käyttäjistäsi :D )! Lisäsin myös luokan, se toimi mainiosti. Luokan poisto taitaa myös olla vielä kesken. Askareiden lisäys ja muokkaus ja poisto lienee myös kesken, napin painallus ei johtanut mihinkään.

Dokumentaatio on hyvin aloitettu, mutta taitaa olla myös hieman jäljessä. Viimeisen kahden sivun teksti on aika irrallaan muusta dokumentaatiosta (ehkä muistilista tekijälle?). 

Yleiskuva sovelluksesta on hyvä, ja keskenhän se vielä on mutta hyvä siitä tulee :) en osaa oikein antaa mitään vinkkejä, sillä olet tehnyt kaiken aikalailla samalla lailla kuin itsekin tekisin. Toivottavasti aika riittää että saat tämän valmiiksi!

P.S. tykkään tavastasi päivittää README:tä muutoksista.

**Comment by Sihuvi84** [comment]
Kiitos paljon palautteestasi.

Tosiaankin, kun latasit projektin, en ollut vielä ehtinyt pushata kaikkia neljännen viikon vaadittuja muutoksia repoon. Olin myöhässä aikataulusta.

Kirjautuminen ei vielä toiminut testaushetkellä, lisäksi muitakin puutteita oli, kuten olitkin huomannut! :)

Dokumentaatiosta lataushetkellä oli menossa versio numero 03 (https://github.com/Sihuvi84/Tsoha-Bootstrap/blob/master/doc/dokumentaatio_03.pdf), joka siis nimellä dokumentaatio_03.doc. Olen versioinut dokumentoinnin, sillä sen avulla on helpompaa nähdä, mitä muutoksia on milloinkin lisätty. Uskon, että olet katsonut ensimmäistä versiota dokumentaatiosta.

Harmi, kun olin myöhässä aikataulusta, niin olet joutunut katselmoimaan erittäin kesken olevaa palautusta. Kiitos kuitenkin tsemppauksesta ja vaivannäöstä! Kävin vilkaisemassa sinun työtäsi, ja se näyttää oikein hyvältä! Jos kiinnostaa vielä, niin tällä hetkellä sovellukseni on jo vähän paremmin aikataulussa kiinni. Aikaa tosin on rajallisesti, että katsotaan, miten käy ;)

**Comment by emmakamarainen** [comment]
Hei,
ajattelinkin että repo on varmaan jäljessä siitä missä vaiheessa olet :) ja joo, hyvinkin olen saattanut katsoa väärä dokumentaatiota... :D  

Tsemppiä loppukiriin!

**Comment by Sihuvi84** [comment]
Kiitos :) Yritän ehtiä kaiken - miten kiire aina onnistuukin hyökkimään? :D Tsemppiä myös sinulle!
